<?php

/**
 * إعدادات لوحات التحكم — مستخرجة من prototype HTML (عناوين + أصول فقط)
 * Guard concept (تصميم فقط — غير مفعّل):
 *   reception → guard:reception
 *   doctor      → guard:doctor
 *   spec        → guard:spec
 *   adjustments → guard:adjustments
 *   costing     → guard:costing
 *   operations  → guard:operations
 *   technical   → guard:technical
 *   admin       → guard:admin
 */
return [
    'table_per_page' => 10,
    'table_fetch_limit' => 1000,

    'home' => [
        'title' => 'نظام إدارة مركز إنتاج الأطراف الصناعية',
        'layout' => 'layouts.app',
        'styles' => ['assets/css/index.css'],
        'scripts' => ['assets/js/pages/index.js'],
        'body_attributes' => '',
        'guard' => null,
    ],
    'reception' => [
        'title' => 'لوحة موظف الاستقبال — مركز الأطراف الصناعية',
        'layout' => 'layouts.reception',
        'default_page' => 'appointments',
        'sidebar' => ['icon' => '📋', 'title' => 'لوحة موظف الاستقبال', 'subtitle' => 'الجدولة والموافقات'],
        'pages' => [
            'appointments' => ['title' => 'جدولة المواعيد', 'icon' => '📅', 'label' => 'جدولة المواعيد'],
            'statistics' => ['title' => 'إحصائيات الاستقبال', 'icon' => '📊', 'label' => 'الإحصائيات'],
            'quote' => ['title' => 'عروض الأسعار', 'icon' => '💰', 'label' => 'عروض الأسعار'],
            // 'delivery' => ['title' => 'تسليم الطرف للمريض', 'icon' => '✅', 'label' => 'تسليم للمريض'], // نُقل لمكتب التشغيل
            'contracts' => ['title' => 'العقود والاتفاقيات', 'icon' => '📑', 'label' => 'العقود والاتفاقيات'],
            'selfservice' => ['title' => 'متابعة حالة الطلب (خدمة ذاتية)', 'icon' => '📱', 'label' => 'متابعة الحالة (خدمة ذاتية)'],
            'patients' => ['title' => 'سجل المرضى المسجلين', 'icon' => '👤', 'label' => 'المرضى'],
            'notifications' => ['title' => 'الإشعارات', 'icon' => '🔔', 'label' => 'الإشعارات'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/charts-kit-static.css', 'assets/css/reception-dashboard.css'],
        'scripts' => [
            'assets/js/shared/export-kit.js',
            'assets/js/shared/charts-kit.js',
            'assets/js/shared/stock-catalog.js',
            'assets/js/shared/cases-workflow.js',
            'assets/js/shared/pricing-queue.js',
            'assets/js/shared/bom-inventory.js',
            'assets/js/pages/reception-dashboard.js',
            'assets/js/pages/reception-statistics.js',
            // 'assets/js/pages/reception-delivery-dashboard.js', // التسليم من مكتب التشغيل
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => '',
        'guard' => 'reception',
    ],
    'doctor' => [
        'title' => 'لوحة الطبيب المعالج — مركز الأطراف الصناعية',
        'layout' => 'layouts.doctor',
        'default_page' => 'queue',
        'sidebar' => ['icon' => '🩺', 'title' => 'لوحة الطبيب المعالج', 'subtitle' => 'العيادة والتشخيص'],
        'pages' => [
            'queue' => ['title' => 'العيادة الطبية — قائمة الانتظار', 'icon' => '📋', 'label' => 'قائمة الانتظار'],
            'diagnosis' => ['title' => 'التشخيص الطبي', 'icon' => '📝', 'label' => 'التشخيص الطبي'],
            'records' => ['title' => 'السجل الطبي — التقارير المعتمدة', 'icon' => '📁', 'label' => 'السجل الطبي'],
            'transfer' => ['title' => 'الحالات المحولة للتوصيف', 'icon' => '📦', 'label' => 'المحولون للتوصيف'],
            'notifications' => ['title' => 'الإشعارات', 'icon' => '🔔', 'label' => 'الإشعارات'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/charts-kit-static.css', 'assets/css/doctor-dashboard.css'],
        'scripts' => [
            'assets/js/shared/export-kit.js',
            'assets/js/shared/charts-kit.js',
            'assets/js/shared/stock-catalog.js',
            'assets/js/shared/stock-multi-select.js',
            'assets/js/pages/doctor-dashboard.js',
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => '',
        'guard' => 'doctor',
    ],
    'spec' => [
        'title' => 'لوحة التوصيف الفني — مركز الأطراف الصناعية',
        'layout' => 'layouts.spec',
        'default_page' => 'orders',
        'sidebar' => ['icon' => '📐', 'title' => 'لوحة التوصيف', 'subtitle' => 'أكواد وكميات – قبل التصنيع'],
        'pages' => [
            'orders' => ['title' => 'طلبات التوصيف', 'icon' => '📥', 'label' => 'طلبات التوصيف'],
            'spec' => ['title' => 'معاينة التوصيف', 'icon' => '👁️', 'label' => 'معاينة التوصيف'],
            'pricing' => ['title' => 'إرسال للتسعير', 'icon' => '💰', 'label' => 'إرسال للتسعير'],
            'notifications' => ['title' => 'الإشعارات', 'icon' => '🔔', 'label' => 'الإشعارات'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/charts-kit-static.css', 'assets/css/technical-dashboard.css'],
        'scripts' => [
            'https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js',
            'assets/js/shared/export-kit.js',
            'assets/js/shared/charts-kit.js',
            'assets/js/pages/spec-dashboard.js',
            'assets/js/pages/spec-edit-preview.js',
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => 'data-dashboard="spec"',
        'guard' => 'spec',
    ],
    'adjustments' => [
        'title' => 'لوحة المعدلات — مركز الأطراف الصناعية',
        'layout' => 'layouts.adjustments',
        'default_page' => 'adjustments',
        'sidebar' => ['icon' => '📏', 'title' => 'لوحة المعدلات', 'subtitle' => 'تجارب التركيب والمقاسات'],
        'pages' => [
            'adjustments' => ['title' => 'المعدلات — تجارب التركيب والمقاسات', 'icon' => '📏', 'label' => 'جدول المعدلات'],
            'history'     => ['title' => 'المحوّلون للتكاليف', 'icon' => '📤', 'label' => 'سجل المحوّلين'],
            'notifications' => ['title' => 'الإشعارات', 'icon' => '🔔', 'label' => 'الإشعارات'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/charts-kit-static.css', 'assets/css/technical-dashboard.css'],
        'scripts' => [
            'https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js',
            'assets/js/shared/export-kit.js',
            'assets/js/pages/adjustments-dashboard.js',
            'assets/js/pages/adjustments-history.js',
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => 'data-dashboard="adjustments"',
        'guard' => 'adjustments',
    ],
    'costing' => [
        'title' => 'لوحة التكاليف — مركز الأطراف الصناعية',
        'layout' => 'layouts.costing',
        'default_page' => 'costing',
        'sidebar' => ['icon' => '💰', 'title' => 'لوحة التكاليف', 'subtitle' => 'مراجعة وإصدار العرض'],
        'pages' => [
            'costing' => ['title' => 'التكاليف', 'icon' => '💰', 'label' => 'التكاليف'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/technical-dashboard.css'],
        'scripts' => [
            'https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js',
            'assets/js/pages/costing-dashboard.js',
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => 'data-dashboard="costing"',
        'guard' => 'costing',
    ],
    'operations' => [
        'title' => 'لوحة التشغيل — مركز الأطراف الصناعية',
        'layout' => 'layouts.operations',
        'default_page' => 'pending',
        'sidebar' => ['icon' => '🎯', 'title' => 'مكتب التشغيل', 'subtitle' => 'الموافقات والتسليم'],
        'pages' => [
            'pending' => ['title' => 'مكتب التشغيل — موافقات وعروض الأسعار', 'icon' => '✅', 'label' => 'موافقات التشغيل'],
            'quotes-awaiting' => ['title' => 'عروض الأسعار — بانتظار موافقة الجهة', 'icon' => '💰', 'label' => 'عروض بانتظار الموافقة'],
            'operations' => ['title' => 'مكتب التشغيل — تسليم الطرف للعميل', 'icon' => '✅', 'label' => 'تسليم للعميل'],
            'notifications' => ['title' => 'الإشعارات', 'icon' => '🔔', 'label' => 'الإشعارات'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/charts-kit-static.css', 'assets/css/technical-dashboard.css'],
        'scripts' => [
            'https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js',
            'assets/js/pages/operations-pending-dashboard.js',
            'assets/js/pages/operations-quotes-awaiting-dashboard.js',
            'assets/js/pages/operations-dashboard.js',
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => 'data-dashboard="operations"',
        'guard' => 'operations',
    ],
    'workshop' => [
        'title' => 'لوحة ورشة التصنيع — مركز الأطراف الصناعية',
        'layout' => 'layouts.workshop',
        'default_page' => 'workshop',
        'sidebar' => ['icon' => '🏭', 'title' => 'ورشة التصنيع', 'subtitle' => 'أوامر الإنتاج والتشغيل'],
        'pages' => [
            'workshop' => ['title' => 'ورشة التصنيع — أوامر تحت التشغيل', 'icon' => '🏭', 'label' => 'طابور الورشة'],
            'returns' => ['title' => 'طلبات ارتجاع المواد — ورشة → مخزن', 'icon' => '↩️', 'label' => 'ارتجاع للمخزن'],
            'statistics' => ['title' => 'إحصائيات الورشة', 'icon' => '📊', 'label' => 'الإحصائيات'],
            'notifications' => ['title' => 'الإشعارات', 'icon' => '🔔', 'label' => 'الإشعارات'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/charts-kit-static.css', 'assets/css/technical-dashboard.css'],
        'scripts' => [
            'https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js',
            'assets/js/shared/export-kit.js',
            'assets/js/shared/charts-kit.js',
            'assets/js/pages/workshop-dashboard.js',
            'assets/js/pages/workshop-returns-dashboard.js',
            'assets/js/pages/workshop-statistics.js',
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => 'data-dashboard="workshop"',
        'guard' => 'workshop',
    ],
    'technical' => [
        'title' => 'لوحة المخزون — مركز الأطراف الصناعية',
        'layout' => 'layouts.technical',
        'default_page' => 'inventory',
        'sidebar' => ['icon' => '📦', 'title' => 'لوحة المخزون', 'subtitle' => 'إدارة الأصناف والكميات'],
        'pages' => [
            'inventory' => ['title' => 'المخزون — الأصناف والكميات', 'icon' => '📦', 'label' => 'المخزون'],
            'bom' => ['title' => 'قوائم صرف المواد — خام / تشغيل / تام', 'icon' => '📋', 'label' => 'صرف المواد للورشة'],
            'returns' => ['title' => 'استلام ارتجاع المواد — من الورشة', 'icon' => '↩️', 'label' => 'استلام الارتجاع'],
            'notifications' => ['title' => 'الإشعارات', 'icon' => '🔔', 'label' => 'الإشعارات'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/charts-kit-static.css', 'assets/css/technical-dashboard.css'],
        'scripts' => [
            'https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js',
            'assets/js/shared/export-kit.js',
            'assets/js/shared/charts-kit.js',
            'assets/js/shared/stock-catalog.js',
            'assets/js/shared/cases-workflow.js',
            'assets/js/shared/pricing-queue.js',
            'assets/js/shared/bom-inventory.js',
            'assets/js/shared/operations-desk.js',
            'assets/js/shared/inventory-returns.js',
            'assets/js/pages/technical-dashboard.js',
            'assets/js/pages/technical-bom-dashboard.js',
            'assets/js/pages/returns-dashboard.js',
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => 'data-dashboard="inventory"',
        'guard' => 'technical',
    ],
    'admin' => [
        'title' => 'لوحة إدارة النظام — مركز الأطراف الصناعية',
        'layout' => 'layouts.admin',
        'default_page' => 'overview',
        'sidebar' => ['icon' => '⚙️', 'title' => 'لوحة إدارة النظام', 'subtitle' => 'المالك والرقابة'],
        'pages' => [
            // ── نظرة عامة وتحليلات ──────────────────────────────────────────────
            'overview' => ['title' => 'لوحة المعلومات — الإدارة العليا', 'icon' => '📊', 'label' => 'نظرة عامة'],
            'bi' => ['title' => 'لوحات القيادة — 5 لوحات', 'icon' => '📡', 'label' => 'لوحات القيادة'],
            'general-view' => ['title' => 'رؤية عامة — مؤشرات لحظية', 'icon' => '📈', 'label' => 'رؤية عامة'],
            'reports' => ['title' => 'التقارير — تصدير وفلترة بالتاريخ', 'icon' => '📋', 'label' => 'التقارير'],
            'reports-section' => ['title' => 'تفاصيل التقرير', 'icon' => '📄', 'label' => 'تفاصيل التقرير', 'hidden' => true],
            // ── مسار المرضى والحالات ───────────────────────────────────────────
            'patient-tracks' => ['title' => 'مسار المرضى — تتبع المراحل', 'icon' => '📍', 'label' => 'مسار المرضى'],
            'spec-edit-requests' => ['title' => 'طلبات تعديل التوصيف', 'icon' => '✏️', 'label' => 'تعديل التوصيف'],
            'cases' => ['title' => 'متابعة الحالات', 'icon' => '📁', 'label' => 'متابعة الحالات'],
            'visit-types' => ['title' => 'أنواع الزيارات', 'icon' => '📋', 'label' => 'أنواع الزيارات'],
            // ── المخزون والتوريد ───────────────────────────────────────────────
            // 'stock-categories' => ['title' => 'فئات الأصناف', 'icon' => '🏷️', 'label' => 'فئات الأصناف'],
            'catalog' => ['title' => 'الأصناف والأسعار', 'icon' => '📦', 'label' => 'الأصناف والأسعار'],
            'inventory-overview' => ['title' => 'لوحة المخزون التفصيلية', 'icon' => '🔬', 'label' => 'المخزون التفصيلي'],
            'suppliers' => ['title' => 'الموردون', 'icon' => '🏭', 'label' => 'الموردون'],
            'returns' => ['title' => 'طلبات ارتجاع المواد — مراقبة وقراءة فقط', 'icon' => '↩️', 'label' => 'طلبات الارتجاع'],
            // ── التعاقد والمالية ───────────────────────────────────────────────
            'companies' => ['title' => 'جهات التعاقد', 'icon' => '🏢', 'label' => 'جهات التعاقد'],
            'contracts' => ['title' => 'موافقات جهات التعاقد — أرشيف الاعتمادات المالية', 'icon' => '📑', 'label' => 'موافقات جهات التعاقد'],
            'civilian-debts' => ['title' => 'مديونيات جهات التعاقد المدنية', 'icon' => '🌐', 'label' => 'مديونيات مدنية'],
            'military-debts' => ['title' => 'مديونيات الجهات العسكرية', 'icon' => '🪖', 'label' => 'مديونيات عسكرية'],
            // ── الرقابة ────────────────────────────────────────────────────────
            'audit' => ['title' => 'سجل الرقابة الحصين — Immutable Audit Log', 'icon' => '🔒', 'label' => 'سجل الرقابة'],
            // ── إدارة النظام ───────────────────────────────────────────────────
            'employees' => ['title' => 'إدارة الموظفين ', 'icon' => '👥', 'label' => 'الموظفون'],
            'permissions' => ['title' => 'مصفوفة الصلاحيات', 'icon' => '🛡️', 'label' => 'الصلاحيات'],
            'military-ranks' => ['title' => 'الرتب العسكرية', 'icon' => '🪖', 'label' => 'الرتب العسكرية'],
            'notifications' => ['title' => 'الإشعارات', 'icon' => '🔔', 'label' => 'الإشعارات'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/charts-kit-static.css', 'assets/css/admin-dashboard.css'],
        'scripts' => [
            'assets/js/shared/export-kit.js',
            'assets/js/shared/debt-collect.js',
            'assets/js/shared/debt-collection-history.js',
            'assets/js/shared/charts-kit.js',
            'assets/js/shared/stock-catalog.js',
            'assets/js/shared/cases-workflow.js',
            'assets/js/shared/bom-inventory.js',
            'assets/js/shared/operations-desk.js',
            'assets/js/shared/bulk-table-select.js',
            'assets/js/pages/admin-dashboard.js',
            'assets/js/pages/admin-spec-edit-requests.js',
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => '',
        'guard' => 'admin',
    ],
];
