<?php

/**
 * إعدادات لوحات التحكم — مستخرجة من prototype HTML (عناوين + أصول فقط)
 * Guard concept (تصميم فقط — غير مفعّل):
 *   reception → guard:reception
 *   doctor      → guard:doctor
 *   spec        → guard:spec
 *   adjustments → guard:adjustments
 *   operations  → guard:operations
 *   technical   → guard:technical
 *   admin       → guard:admin
 */
return [
    'table_per_page' => 10,
    'table_fetch_limit' => 1000,

    'home' => [
        'title' => 'نظام إدارة مركز إنتاج الأطراف الصناعية',
        'layout' => 'layouts.app',
        'styles' => ['assets/css/index.css'],
        'scripts' => ['assets/js/pages/index.js'],
        'body_attributes' => '',
        'guard' => null,
    ],
    'reception' => [
        'title' => 'لوحة موظف الاستقبال — مركز الأطراف الصناعية',
        'layout' => 'layouts.reception',
        'default_page' => 'appointments',
        'sidebar' => ['icon' => '📋', 'title' => 'لوحة موظف الاستقبال', 'subtitle' => 'الجدولة والموافقات'],
        'pages' => [
            'appointments' => ['title' => 'جدولة المواعيد', 'icon' => '📅', 'label' => 'جدولة المواعيد'],
            'quote' => ['title' => 'عروض الأسعار', 'icon' => '💰', 'label' => 'عروض الأسعار'],
            'delivery' => ['title' => 'تسليم الطرف للمريض', 'icon' => '✅', 'label' => 'تسليم للمريض'],
            'contracts' => ['title' => 'العقود والاتفاقيات', 'icon' => '📑', 'label' => 'العقود والاتفاقيات'],
            'selfservice' => ['title' => 'متابعة حالة الطلب (خدمة ذاتية)', 'icon' => '📱', 'label' => 'متابعة الحالة (خدمة ذاتية)'],
            'patients' => ['title' => 'سجل المرضى المسجلين', 'icon' => '👤', 'label' => 'المرضى'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/charts-kit-static.css', 'assets/css/reception-dashboard.css'],
        'scripts' => [
            'assets/js/shared/export-kit.js',
            'assets/js/shared/charts-kit.js',
            'assets/js/shared/stock-catalog.js',
            'assets/js/shared/cases-workflow.js',
            'assets/js/shared/pricing-queue.js',
            'assets/js/shared/bom-inventory.js',
            'assets/js/pages/reception-dashboard.js',
            'assets/js/pages/reception-delivery-dashboard.js',
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => '',
        'guard' => 'reception',
    ],
    'doctor' => [
        'title' => 'لوحة الطبيب المعالج — مركز الأطراف الصناعية',
        'layout' => 'layouts.doctor',
        'default_page' => 'queue',
        'sidebar' => ['icon' => '🩺', 'title' => 'لوحة الطبيب المعالج', 'subtitle' => 'العيادة والتشخيص'],
        'pages' => [
            'queue' => ['title' => 'العيادة الطبية — قائمة الانتظار', 'icon' => '📋', 'label' => 'قائمة الانتظار'],
            'diagnosis' => ['title' => 'التشخيص الطبي', 'icon' => '📝', 'label' => 'التشخيص الطبي'],
            'records' => ['title' => 'السجل الطبي — التقارير المعتمدة', 'icon' => '📁', 'label' => 'السجل الطبي'],
            'transfer' => ['title' => 'الحالات المحولة للتوصيف', 'icon' => '📦', 'label' => 'المحولون للتوصيف'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/charts-kit-static.css', 'assets/css/doctor-dashboard.css'],
        'scripts' => [
            'assets/js/shared/export-kit.js',
            'assets/js/shared/charts-kit.js',
            'assets/js/shared/stock-catalog.js',
            'assets/js/shared/stock-multi-select.js',
            'assets/js/pages/doctor-dashboard.js',
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => '',
        'guard' => 'doctor',
    ],
    'spec' => [
        'title' => 'لوحة التوصيف الفني — مركز الأطراف الصناعية',
        'layout' => 'layouts.spec',
        'default_page' => 'orders',
        'sidebar' => ['icon' => '📐', 'title' => 'لوحة التوصيف', 'subtitle' => 'أكواد وكميات – قبل التصنيع'],
        'pages' => [
            'orders' => ['title' => 'طلبات التوصيف', 'icon' => '📥', 'label' => 'طلبات التوصيف'],
            'spec' => ['title' => 'معاينة التوصيف', 'icon' => '👁️', 'label' => 'معاينة التوصيف'],
            'pricing' => ['title' => 'إرسال للتسعير', 'icon' => '💰', 'label' => 'إرسال للتسعير'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/charts-kit-static.css', 'assets/css/technical-dashboard.css'],
        'scripts' => [
            'https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js',
            'assets/js/shared/export-kit.js',
            'assets/js/shared/charts-kit.js',
            'assets/js/pages/spec-dashboard.js',
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => 'data-dashboard="spec"',
        'guard' => 'spec',
    ],
    'adjustments' => [
        'title' => 'لوحة المعدلات — مركز الأطراف الصناعية',
        'layout' => 'layouts.adjustments',
        'default_page' => 'adjustments',
        'sidebar' => ['icon' => '📏', 'title' => 'لوحة المعدلات', 'subtitle' => 'تجارب التركيب والمقاسات'],
        'pages' => [
            'adjustments' => ['title' => 'المعدلات — تجارب التركيب والمقاسات', 'icon' => '📏', 'label' => 'جدول المعدلات'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/charts-kit-static.css', 'assets/css/technical-dashboard.css'],
        'scripts' => [
            'https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js',
            'assets/js/pages/adjustments-dashboard.js',
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => 'data-dashboard="adjustments"',
        'guard' => 'adjustments',
    ],
    'operations' => [
        'title' => 'لوحة التشغيل — مركز الأطراف الصناعية',
        'layout' => 'layouts.operations',
        'default_page' => 'operations',
        'sidebar' => ['icon' => '🎯', 'title' => 'مكتب التشغيل', 'subtitle' => 'أوامر الإنتاج والصرف'],
        'pages' => [
            'operations' => ['title' => 'مكتب التشغيل — أوامر الصرف والإنتاج', 'icon' => '🎯', 'label' => 'أوامر التشغيل'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/charts-kit-static.css', 'assets/css/technical-dashboard.css'],
        'scripts' => [
            'https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js',
            'assets/js/pages/operations-dashboard.js',
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => '',
        'guard' => 'operations',
    ],
    'technical' => [
        'title' => 'لوحة المخزون — مركز الأطراف الصناعية',
        'layout' => 'layouts.technical',
        'default_page' => 'inventory',
        'sidebar' => ['icon' => '📦', 'title' => 'لوحة المخزون', 'subtitle' => 'إدارة الأصناف والكميات'],
        'pages' => [
            'inventory' => ['title' => 'المخزون — الأصناف والكميات', 'icon' => '📦', 'label' => 'المخزون'],
            'bom' => ['title' => 'BOM — خام / تشغيل / تام', 'icon' => '📋', 'label' => 'BOM — خام / تشغيل / تام'],
            'returns' => ['title' => 'إذن ارتجاع', 'icon' => '↩️', 'label' => 'إذن ارتجاع'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/charts-kit-static.css', 'assets/css/technical-dashboard.css'],
        'scripts' => [
            'https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js',
            'assets/js/shared/export-kit.js',
            'assets/js/shared/charts-kit.js',
            'assets/js/shared/stock-catalog.js',
            'assets/js/shared/cases-workflow.js',
            'assets/js/shared/pricing-queue.js',
            'assets/js/shared/bom-inventory.js',
            'assets/js/shared/operations-desk.js',
            'assets/js/shared/inventory-returns.js',
            'assets/js/pages/technical-dashboard.js',
            'assets/js/pages/technical-bom-dashboard.js',
            'assets/js/pages/returns-dashboard.js',
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => 'data-dashboard="inventory"',
        'guard' => 'technical',
    ],
    'admin' => [
        'title' => 'لوحة إدارة النظام — مركز الأطراف الصناعية',
        'layout' => 'layouts.admin',
        'default_page' => 'overview',
        'sidebar' => ['icon' => '⚙️', 'title' => 'لوحة إدارة النظام', 'subtitle' => 'المالك والرقابة'],
        'pages' => [
            'overview' => ['title' => 'لوحة المعلومات — الإدارة العليا', 'icon' => '📊', 'label' => 'نظرة عامة'],
            'bi' => ['title' => 'لوحات القيادة (BI) — 5 لوحات', 'icon' => '📡', 'label' => 'لوحات القيادة (BI)'],
            'catalog' => ['title' => 'الأصناف والأسعار', 'icon' => '📦', 'label' => 'الأصناف والأسعار'],
            'stock-categories' => ['title' => 'فئات الأصناف', 'icon' => '🏷️', 'label' => 'فئات الأصناف'],
            'pricing' => ['title' => 'اعتماد طلبات التسعير', 'icon' => '✅', 'label' => 'اعتماد التسعير'],
            'cases' => ['title' => 'متابعة الحالات', 'icon' => '📁', 'label' => 'متابعة الحالات'],
            'employees' => ['title' => 'إدارة الموظفين ', 'icon' => '👥', 'label' => 'الموظفون'],
            'companies' => ['title' => 'جهات التعاقد', 'icon' => '🏢', 'label' => 'جهات التعاقد'],
            'military-debts' => ['title' => 'مديونيات الجهات العسكرية', 'icon' => '🪖', 'label' => 'مديونيات عسكرية'],
            'returns' => ['title' => 'مراقبة ارتجاع المواد — ورشة → مخزن', 'icon' => '↩️', 'label' => 'ارتجاع المواد'],
            'audit' => ['title' => 'سجل الرقابة الحصين — Immutable Audit Log', 'icon' => '🔒', 'label' => 'سجل الرقابة'],
            'reports' => ['title' => 'التقارير والتحليلات', 'icon' => '📈', 'label' => 'التقارير'],
            'suppliers' => ['title' => 'الموردون', 'icon' => '🏭', 'label' => 'الموردون'],
            'contracts' => ['title' => 'العقود والاتفاقيات — أرشيف الاعتمادات المالية', 'icon' => '📑', 'label' => 'العقود والاتفاقيات'],
            'military-ranks' => ['title' => 'الرتب العسكرية', 'icon' => '🪖', 'label' => 'الرتب العسكرية'],
            'visit-types' => ['title' => 'أنواع الزيارات', 'icon' => '📋', 'label' => 'أنواع الزيارات'],
        ],
        'styles' => ['assets/css/dashboard-mobile.css', 'assets/css/charts-kit-static.css', 'assets/css/admin-dashboard.css'],
        'scripts' => [
            'assets/js/shared/export-kit.js',
            'assets/js/shared/charts-kit.js',
            'assets/js/shared/stock-catalog.js',
            'assets/js/shared/cases-workflow.js',
            'assets/js/shared/pricing-queue.js',
            'assets/js/shared/bom-inventory.js',
            'assets/js/shared/operations-desk.js',
            'assets/js/shared/bulk-table-select.js',
            'assets/js/pages/admin-dashboard.js',
            'assets/js/shared/dashboard-mobile.js',
        ],
        'body_attributes' => '',
        'guard' => 'admin',
    ],
];
