<?php

/**
 * كتالوج الوثائق القابلة للتخصيص — الافتراضيات والحقول في محرر مركز الوثائق.
 *
 * @return array{
 *     definitions: array<string, array{
 *         group: string,
 *         title: string,
 *         description: string,
 *         view: string,
 *         print_route: ?string,
 *         fields: list<array{key: string, label: string, type: string, help?: string}>,
 *         defaults: array<string, mixed>
 *     }>
 * }
 */
return [
    'definitions' => [
        'quote' => [
            'group' => 'المالية والاستقبال',
            'title' => 'عرض سعر',
            'description' => 'طباعة عرض السعر للمريض / الجهة',
            'view' => 'quotes.print',
            'print_route' => null,
            'fields' => [
                ['key' => 'doc_title', 'label' => 'عنوان الوثيقة', 'type' => 'text'],
                ['key' => 'dept_label', 'label' => 'اسم القسم في الترويسة', 'type' => 'text'],
                ['key' => 'subtitle', 'label' => 'سطر توضيحي تحت العنوان', 'type' => 'text'],
                ['key' => 'footer_note', 'label' => 'ملاحظة أسفل الوثيقة', 'type' => 'textarea'],
                ['key' => 'signature_1', 'label' => 'توقيع 1', 'type' => 'text'],
                ['key' => 'signature_2', 'label' => 'توقيع 2', 'type' => 'text'],
                ['key' => 'show_logo', 'label' => 'إظهار الشعار', 'type' => 'bool'],
                ['key' => 'show_seal', 'label' => 'إظهار الختم', 'type' => 'bool'],
                ['key' => 'compact_layout', 'label' => 'تنسيق مضغوط (ورقة واحدة)', 'type' => 'bool'],
            ],
            'defaults' => [
                'doc_title' => 'عرض سعر',
                'dept_label' => 'قسم الاستقبال والمالية',
                'subtitle' => '',
                'footer_note' => '',
                'signature_1' => 'مسؤول الاستقبال',
                'signature_2' => 'يعتمد — مدير المركز',
                'show_logo' => true,
                'show_seal' => true,
                'compact_layout' => true,
                'font_scale' => 'compact',
            ],
        ],
        'payment_receipt' => [
            'group' => 'المالية والاستقبال',
            'title' => 'إيصال دفع',
            'description' => 'إيصال الخزنة بعد التحصيل',
            'view' => 'prints.payment-receipt',
            'print_route' => null,
            'fields' => [
                ['key' => 'doc_title', 'label' => 'عنوان الوثيقة', 'type' => 'text'],
                ['key' => 'dept_label', 'label' => 'اسم القسم في الترويسة', 'type' => 'text'],
                ['key' => 'subtitle', 'label' => 'سطر توضيحي', 'type' => 'text'],
                ['key' => 'footer_note', 'label' => 'ملاحظة أسفل الإيصال', 'type' => 'textarea'],
                ['key' => 'signature_1', 'label' => 'توقيع المحصل', 'type' => 'text'],
                ['key' => 'signature_2', 'label' => 'توقيع المستلم', 'type' => 'text'],
                ['key' => 'show_logo', 'label' => 'إظهار الشعار', 'type' => 'bool'],
                ['key' => 'show_seal', 'label' => 'إظهار الختم', 'type' => 'bool'],
                ['key' => 'compact_layout', 'label' => 'تنسيق مضغوط', 'type' => 'bool'],
            ],
            'defaults' => [
                'doc_title' => 'إيصال استلام نقدية',
                'dept_label' => 'الخزنة',
                'subtitle' => 'إيصال دفع — مركز الأطراف الصناعية',
                'footer_note' => '',
                'signature_1' => 'أمين الخزنة',
                'signature_2' => 'المستلم',
                'show_logo' => true,
                'show_seal' => true,
                'compact_layout' => true,
                'font_scale' => 'compact',
            ],
        ],
        'issue_voucher' => [
            'group' => 'المخزن والتوريد',
            'title' => 'إذن صرف مواد',
            'description' => 'صرف BOM لقسم الإنتاج — من المخزن',
            'view' => 'prints.issue-voucher',
            'print_route' => null,
            'fields' => [
                ['key' => 'doc_title', 'label' => 'عنوان الوثيقة', 'type' => 'text', 'help' => 'استخدم {no} لرقم الإذن'],
                ['key' => 'dept_label', 'label' => 'اسم القسم في الترويسة', 'type' => 'text'],
                ['key' => 'intro_line', 'label' => 'مقدمة قسم البنود', 'type' => 'text'],
                ['key' => 'spec_section_title', 'label' => 'عنوان قسم التوصيف', 'type' => 'text'],
                ['key' => 'footer_note', 'label' => 'ملاحظة أسفل الوثيقة', 'type' => 'textarea'],
                ['key' => 'signature_1', 'label' => 'توقيع 1 (فني)', 'type' => 'text'],
                ['key' => 'signature_2', 'label' => 'توقيع 2', 'type' => 'text'],
                ['key' => 'signature_3', 'label' => 'توقيع 3', 'type' => 'text'],
                ['key' => 'signature_4', 'label' => 'توقيع 4 (المخازن)', 'type' => 'text'],
                ['key' => 'show_spec_section', 'label' => 'إظهار قسم التوصيف', 'type' => 'bool'],
                ['key' => 'show_logo', 'label' => 'إظهار الشعار', 'type' => 'bool'],
                ['key' => 'show_seal', 'label' => 'إظهار الختم', 'type' => 'bool'],
                ['key' => 'compact_layout', 'label' => 'تنسيق مضغوط', 'type' => 'bool'],
            ],
            'defaults' => [
                'doc_title' => 'إذن صرف مواد — رقم ( {no} )',
                'dept_label' => 'قسم المخازن',
                'intro_line' => 'مواد الصرف لقسم الإنتاج (مطابقة التوصيف أعلاه):',
                'spec_section_title' => 'الطرف الصناعي — التوصيف (غير منفصل عن إذن الصرف)',
                'footer_note' => '',
                'signature_1' => 'الفني المختص',
                'signature_2' => 'مدير الإنتاج',
                'signature_3' => 'قائد المصنع',
                'signature_4' => 'رئيس المخازن',
                'show_spec_section' => true,
                'show_logo' => true,
                'show_seal' => true,
                'compact_layout' => true,
                'font_scale' => 'compact',
            ],
        ],
        'supply_request_list' => [
            'group' => 'المخزن والتوريد',
            'title' => 'طلبات التوريد المفتوحة',
            'description' => 'قائمة طلبات التوريد مع التواريخ',
            'view' => 'prints.supply-request-list',
            'print_route' => 'admin.supply.requests.print',
            'fields' => [
                ['key' => 'doc_title', 'label' => 'عنوان الوثيقة', 'type' => 'text'],
                ['key' => 'dept_label', 'label' => 'اسم القسم في الترويسة', 'type' => 'text'],
                ['key' => 'subtitle', 'label' => 'سطر توضيحي', 'type' => 'text'],
                ['key' => 'footer_note', 'label' => 'ملاحظة أسفل القائمة', 'type' => 'textarea'],
                ['key' => 'signature_1', 'label' => 'توقيع يعتمد', 'type' => 'text'],
                ['key' => 'show_logo', 'label' => 'إظهار الشعار', 'type' => 'bool'],
                ['key' => 'show_seal', 'label' => 'إظهار الختم', 'type' => 'bool'],
                ['key' => 'compact_layout', 'label' => 'تنسيق مضغوط', 'type' => 'bool'],
            ],
            'defaults' => [
                'doc_title' => 'طلبات التوريد المفتوحة',
                'dept_label' => 'قسم المخازن',
                'subtitle' => 'البنود بانتظار التوريد أو جاهزة للاستلام',
                'footer_note' => '',
                'signature_1' => 'رئيس المخازن',
                'show_logo' => true,
                'show_seal' => true,
                'compact_layout' => true,
                'font_scale' => 'compact',
            ],
        ],
        'work_order' => [
            'group' => 'الإنتاج والتصنيع',
            'title' => 'إذن شغل',
            'description' => 'أمر التشغيل لقسم الإنتاج',
            'view' => 'prints.work-order',
            'print_route' => null,
            'fields' => [
                ['key' => 'doc_title', 'label' => 'عنوان الوثيقة', 'type' => 'text'],
                ['key' => 'dept_label', 'label' => 'اسم القسم في الترويسة', 'type' => 'text'],
                ['key' => 'items_section_title', 'label' => 'عنوان جدول البنود', 'type' => 'text'],
                ['key' => 'footer_note', 'label' => 'ملاحظة المصنع', 'type' => 'textarea'],
                ['key' => 'signature_1', 'label' => 'موظف مختص', 'type' => 'text'],
                ['key' => 'signature_2', 'label' => 'رئيس القسم', 'type' => 'text'],
                ['key' => 'signature_3', 'label' => 'مدير الإنتاج', 'type' => 'text'],
                ['key' => 'show_logo', 'label' => 'إظهار الشعار', 'type' => 'bool'],
                ['key' => 'show_seal', 'label' => 'إظهار الختم', 'type' => 'bool'],
                ['key' => 'compact_layout', 'label' => 'تنسيق مضغوط', 'type' => 'bool'],
            ],
            'defaults' => [
                'doc_title' => 'إذن شغل',
                'dept_label' => 'قسم الإنتاج — إذن شغل',
                'items_section_title' => 'المواصفات / بنود العمل',
                'footer_note' => '',
                'signature_1' => 'الموظف المختص',
                'signature_2' => 'رئيس القسم',
                'signature_3' => 'مدير الإنتاج',
                'show_logo' => true,
                'show_seal' => true,
                'compact_layout' => true,
                'font_scale' => 'compact',
            ],
        ],
        'spec_print' => [
            'group' => 'الإنتاج والتصنيع',
            'title' => 'تقرير التوصيف',
            'description' => 'طباعة التوصيف الفني',
            'view' => null,
            'print_route' => null,
            'fields' => [
                ['key' => 'doc_title', 'label' => 'عنوان الوثيقة', 'type' => 'text'],
                ['key' => 'dept_label', 'label' => 'اسم القسم في الترويسة', 'type' => 'text'],
                ['key' => 'footer_note', 'label' => 'ملاحظة أسفل التقرير', 'type' => 'textarea'],
                ['key' => 'signature_1', 'label' => 'توقيع 1', 'type' => 'text'],
                ['key' => 'signature_2', 'label' => 'توقيع 2', 'type' => 'text'],
                ['key' => 'show_logo', 'label' => 'إظهار الشعار', 'type' => 'bool'],
                ['key' => 'show_seal', 'label' => 'إظهار الختم', 'type' => 'bool'],
                ['key' => 'compact_layout', 'label' => 'تنسيق مضغوط', 'type' => 'bool'],
            ],
            'defaults' => [
                'doc_title' => 'تقرير التوصيف الفني',
                'dept_label' => 'قسم التوصيف',
                'footer_note' => '',
                'signature_1' => 'أخصائي التوصيف',
                'signature_2' => 'رئيس قسم التوصيف',
                'show_logo' => true,
                'show_seal' => true,
                'compact_layout' => true,
                'font_scale' => 'compact',
            ],
        ],
    ],
];
